{
  'variables': {
    'relative_dir': 'src/test',
    'gen_out_dir': '<(SHARED_INTERMEDIATE_DIR)/<(relative_dir)',
    'out_dir': '<(PRODUCT_DIR)',
    'backend_dir': '../../../../src',
    'bridge_dir': '<(backend_dir)/bridge',
    'engine_dir': '<(backend_dir)/engine',
    'tests_dir': '<(engine_dir)/tests',
    'inc': [
        './',
        '<(bridge_dir)',
        '<(engine_dir)/backend',
        '<(engine_dir)/completer',
        '<(engine_dir)/dictionary',
        '<(engine_dir)/editor',
        '<(engine_dir)/entry',
        '<(engine_dir)/keymap',
        '<(engine_dir)/selector',
        '<(engine_dir)/session',
        '<(engine_dir)/skkserv',
        '<(engine_dir)/state',
        '<(engine_dir)/trie',
        '<(engine_dir)/utility',
    ]
  },
  'targets': [
    {
      'target_name': 'calculator_test',
      'type': 'executable',
      'dependencies': [
        '../method/method.gyp:engine_lib',
      ],
      'include_dirs': [
        '<(engine_dir)/utility',
      ],
      'link_settings': {
        'libraries': [
          #'-lbe',
        ],
      },
      'sources': [
        '<(tests_dir)/calculator_TEST.cpp',
      ],
    },
    
    {
      'target_name': 'skkbackend_test',
      'type': 'executable',
      'dependencies': [
        '../method/method.gyp:engine_lib',
      ],
      'include_dirs': [
        './',
        '<(bridge_dir)',
        '<(engine_dir)/backend',
        '<(engine_dir)/completer',
        '<(engine_dir)/dictionary',
        '<(engine_dir)/editor',
        '<(engine_dir)/entry',
        '<(engine_dir)/keymap',
        '<(engine_dir)/selector',
        '<(engine_dir)/session',
        '<(engine_dir)/skkserv',
        '<(engine_dir)/state',
        '<(engine_dir)/trie',
        '<(engine_dir)/utility',
      ],
      'sources': [
        '<(tests_dir)/SKKBackEnd_TEST.cpp',
      ],
    },
    
    {
      'target_name': 'skkcandidate_test',
      'type': 'executable',
      'dependencies': [
        '../method/method.gyp:engine_lib',
      ],
      'include_dirs': [
        './',
        '<(bridge_dir)',
        '<(engine_dir)/backend',
        '<(engine_dir)/completer',
        '<(engine_dir)/dictionary',
        '<(engine_dir)/editor',
        '<(engine_dir)/entry',
        '<(engine_dir)/keymap',
        '<(engine_dir)/selector',
        '<(engine_dir)/session',
        '<(engine_dir)/skkserv',
        '<(engine_dir)/state',
        '<(engine_dir)/trie',
        '<(engine_dir)/utility',
      ],
      'sources': [
        '<(tests_dir)/SKKCandidate_TEST.cpp',
      ],
    },
    
    {
      'target_name': 'skkcandidateparser_test',
      'type': 'executable',
      'dependencies': [
        '../method/method.gyp:engine_lib',
      ],
      'include_dirs': [
        './',
        '<(bridge_dir)',
        '<(engine_dir)/backend',
        '<(engine_dir)/completer',
        '<(engine_dir)/dictionary',
        '<(engine_dir)/editor',
        '<(engine_dir)/entry',
        '<(engine_dir)/keymap',
        '<(engine_dir)/selector',
        '<(engine_dir)/session',
        '<(engine_dir)/skkserv',
        '<(engine_dir)/state',
        '<(engine_dir)/trie',
        '<(engine_dir)/utility',
      ],
      'sources': [
        '<(tests_dir)/SKKCandidateParser_TEST.cpp',
      ],
    },
    
    {
      'target_name': 'skkcandidatesuite_test',
      'type': 'executable',
      'dependencies': [
        '../method/method.gyp:engine_lib',
      ],
      'include_dirs': [
        './',
        '<(bridge_dir)',
        '<(engine_dir)/backend',
        '<(engine_dir)/completer',
        '<(engine_dir)/dictionary',
        '<(engine_dir)/editor',
        '<(engine_dir)/entry',
        '<(engine_dir)/keymap',
        '<(engine_dir)/selector',
        '<(engine_dir)/session',
        '<(engine_dir)/skkserv',
        '<(engine_dir)/state',
        '<(engine_dir)/trie',
        '<(engine_dir)/utility',
      ],
      'sources': [
        '<(tests_dir)/SKKCandidateSuite_TEST.cpp',
      ],
    },
    
    {
      'target_name': 'skkcommondictionary_test',
      'type': 'executable',
      'dependencies': [
        '../method/method.gyp:engine_lib',
      ],
      'include_dirs': [
        './',
        '<(bridge_dir)',
        '<(engine_dir)/backend',
        '<(engine_dir)/completer',
        '<(engine_dir)/dictionary',
        '<(engine_dir)/editor',
        '<(engine_dir)/entry',
        '<(engine_dir)/keymap',
        '<(engine_dir)/selector',
        '<(engine_dir)/session',
        '<(engine_dir)/skkserv',
        '<(engine_dir)/state',
        '<(engine_dir)/trie',
        '<(engine_dir)/utility',
      ],
      'sources': [
        '<(tests_dir)/SKKCommonDictionary_TEST.cpp',
      ],
    },
    
    {
      'target_name': 'skkcompleter_test',
      'type': 'executable',
      'dependencies': [
        '../method/method.gyp:engine_lib',
      ],
      'include_dirs': [
        './',
        '<(bridge_dir)',
        '<(engine_dir)/backend',
        '<(engine_dir)/completer',
        '<(engine_dir)/dictionary',
        '<(engine_dir)/editor',
        '<(engine_dir)/entry',
        '<(engine_dir)/keymap',
        '<(engine_dir)/selector',
        '<(engine_dir)/session',
        '<(engine_dir)/skkserv',
        '<(engine_dir)/state',
        '<(engine_dir)/trie',
        '<(engine_dir)/utility',
      ],
      'sources': [
        '<(tests_dir)/SKKCompleter_TEST.cpp',
      ],
    },
    
    {
      'target_name': 'skkdictionaryfactory_test',
      'type': 'executable',
      'dependencies': [
        '../method/method.gyp:engine_lib',
      ],
      'include_dirs': [
        './',
        '<(bridge_dir)',
        '<(engine_dir)/backend',
        '<(engine_dir)/completer',
        '<(engine_dir)/dictionary',
        '<(engine_dir)/editor',
        '<(engine_dir)/entry',
        '<(engine_dir)/keymap',
        '<(engine_dir)/selector',
        '<(engine_dir)/session',
        '<(engine_dir)/skkserv',
        '<(engine_dir)/state',
        '<(engine_dir)/trie',
        '<(engine_dir)/utility',
      ],
      'sources': [
        '<(tests_dir)/SKKDictionaryFactory_TEST.cpp',
      ],
    },
    
    {
      'target_name': 'skkdictionaryfile_test',
      'type': 'executable',
      'dependencies': [
        '../method/method.gyp:engine_lib',
      ],
      'include_dirs': [
        './',
        '<(bridge_dir)',
        '<(engine_dir)/backend',
        '<(engine_dir)/completer',
        '<(engine_dir)/dictionary',
        '<(engine_dir)/editor',
        '<(engine_dir)/entry',
        '<(engine_dir)/keymap',
        '<(engine_dir)/selector',
        '<(engine_dir)/session',
        '<(engine_dir)/skkserv',
        '<(engine_dir)/state',
        '<(engine_dir)/trie',
        '<(engine_dir)/utility',
      ],
      'sources': [
        '<(tests_dir)/SKKDictionaryFile_TEST.cpp',
      ],
    },
    
    {
      'target_name': 'skkdictionarykeeper_test',
      'type': 'executable',
      'dependencies': [
        '../method/method.gyp:engine_lib',
      ],
      'include_dirs': [
        './',
        '<(bridge_dir)',
        '<(engine_dir)/backend',
        '<(engine_dir)/completer',
        '<(engine_dir)/dictionary',
        '<(engine_dir)/editor',
        '<(engine_dir)/entry',
        '<(engine_dir)/keymap',
        '<(engine_dir)/selector',
        '<(engine_dir)/session',
        '<(engine_dir)/skkserv',
        '<(engine_dir)/state',
        '<(engine_dir)/trie',
        '<(engine_dir)/utility',
      ],
      'sources': [
        '<(tests_dir)/SKKDictionaryKeeper_TEST.cpp',
      ],
    },
    
    {
      'target_name': 'skkdictionaryloader_test',
      'type': 'executable',
      'dependencies': [
        '../method/method.gyp:engine_lib',
      ],
      'include_dirs': [
        './',
        '<(bridge_dir)',
        '<(engine_dir)/backend',
        '<(engine_dir)/completer',
        '<(engine_dir)/dictionary',
        '<(engine_dir)/editor',
        '<(engine_dir)/entry',
        '<(engine_dir)/keymap',
        '<(engine_dir)/selector',
        '<(engine_dir)/session',
        '<(engine_dir)/skkserv',
        '<(engine_dir)/state',
        '<(engine_dir)/trie',
        '<(engine_dir)/utility',
      ],
      'sources': [
        '<(tests_dir)/SKKDictionaryLoader_TEST.cpp',
      ],
    },
    
    {
      'target_name': 'skkdistributeduserdictionary_test',
      'type': 'executable',
      'dependencies': [
        '../method/method.gyp:engine_lib',
      ],
      'include_dirs': [
        './',
        '<(bridge_dir)',
        '<(engine_dir)/backend',
        '<(engine_dir)/completer',
        '<(engine_dir)/dictionary',
        '<(engine_dir)/editor',
        '<(engine_dir)/entry',
        '<(engine_dir)/keymap',
        '<(engine_dir)/selector',
        '<(engine_dir)/session',
        '<(engine_dir)/skkserv',
        '<(engine_dir)/state',
        '<(engine_dir)/trie',
        '<(engine_dir)/utility',
      ],
      'sources': [
        '<(tests_dir)/SKKDistributedUserDictionary_TEST.cpp',
      ],
    },
    
    {
      'target_name': 'skkgadgetdictionary_test',
      'type': 'executable',
      'dependencies': [
        '../method/method.gyp:engine_lib',
      ],
      'include_dirs': [
        './',
        '<(bridge_dir)',
        '<(engine_dir)/backend',
        '<(engine_dir)/completer',
        '<(engine_dir)/dictionary',
        '<(engine_dir)/editor',
        '<(engine_dir)/entry',
        '<(engine_dir)/keymap',
        '<(engine_dir)/selector',
        '<(engine_dir)/session',
        '<(engine_dir)/skkserv',
        '<(engine_dir)/state',
        '<(engine_dir)/trie',
        '<(engine_dir)/utility',
      ],
      'sources': [
        '<(tests_dir)/SKKGadgetDictionary_TEST.cpp',
      ],
    },
    
    {
      'target_name': 'skkinlineselector_test',
      'type': 'executable',
      'dependencies': [
        '../method/method.gyp:engine_lib',
      ],
      'include_dirs': [
        './',
        '<(bridge_dir)',
        '<(engine_dir)/backend',
        '<(engine_dir)/completer',
        '<(engine_dir)/dictionary',
        '<(engine_dir)/editor',
        '<(engine_dir)/entry',
        '<(engine_dir)/keymap',
        '<(engine_dir)/selector',
        '<(engine_dir)/session',
        '<(engine_dir)/skkserv',
        '<(engine_dir)/state',
        '<(engine_dir)/trie',
        '<(engine_dir)/utility',
      ],
      'sources': [
        '<(tests_dir)/SKKInlineSelector_TEST.cpp',
      ],
    },
    
    {
      'target_name': 'skkinputqueue_test',
      'type': 'executable',
      'dependencies': [
        '../method/method.gyp:engine_lib',
      ],
      'include_dirs': [
        './',
        '<(bridge_dir)',
        '<(engine_dir)/backend',
        '<(engine_dir)/completer',
        '<(engine_dir)/dictionary',
        '<(engine_dir)/editor',
        '<(engine_dir)/entry',
        '<(engine_dir)/keymap',
        '<(engine_dir)/selector',
        '<(engine_dir)/session',
        '<(engine_dir)/skkserv',
        '<(engine_dir)/state',
        '<(engine_dir)/trie',
        '<(engine_dir)/utility',
      ],
      'sources': [
        '<(tests_dir)/SKKInputQueue_TEST.cpp',
      ],
    },
    
    {
      'target_name': 'skkinputsession_test',
      'type': 'executable',
      'dependencies': [
        '../method/method.gyp:engine_lib',
      ],
      'include_dirs': [
        './',
        '<(bridge_dir)',
        '<(engine_dir)/backend',
        '<(engine_dir)/completer',
        '<(engine_dir)/dictionary',
        '<(engine_dir)/editor',
        '<(engine_dir)/entry',
        '<(engine_dir)/keymap',
        '<(engine_dir)/selector',
        '<(engine_dir)/session',
        '<(engine_dir)/skkserv',
        '<(engine_dir)/state',
        '<(engine_dir)/trie',
        '<(engine_dir)/utility',
      ],
      'sources': [
        '<(tests_dir)/SKKInputSession_TEST.cpp',
      ],
    },
    
    {
      'target_name': 'skkkeymap_test',
      'type': 'executable',
      'dependencies': [
        '../method/method.gyp:engine_lib',
      ],
      'include_dirs': [
        './',
        '<(bridge_dir)',
        '<(engine_dir)/backend',
        '<(engine_dir)/completer',
        '<(engine_dir)/dictionary',
        '<(engine_dir)/editor',
        '<(engine_dir)/entry',
        '<(engine_dir)/keymap',
        '<(engine_dir)/selector',
        '<(engine_dir)/session',
        '<(engine_dir)/skkserv',
        '<(engine_dir)/state',
        '<(engine_dir)/trie',
        '<(engine_dir)/utility',
      ],
      'sources': [
        '<(tests_dir)/SKKKeymap_TEST.cpp',
      ],
    },
    
    {
      'target_name': 'skkkeymapentry_test',
      'type': 'executable',
      'dependencies': [
        '../method/method.gyp:engine_lib',
      ],
      'include_dirs': [
        './',
        '<(bridge_dir)',
        '<(engine_dir)/backend',
        '<(engine_dir)/completer',
        '<(engine_dir)/dictionary',
        '<(engine_dir)/editor',
        '<(engine_dir)/entry',
        '<(engine_dir)/keymap',
        '<(engine_dir)/selector',
        '<(engine_dir)/session',
        '<(engine_dir)/skkserv',
        '<(engine_dir)/state',
        '<(engine_dir)/trie',
        '<(engine_dir)/utility',
      ],
      'sources': [
        '<(tests_dir)/SKKKeymapEntry_TEST.cpp',
      ],
    },
    
    {
      'target_name': 'skknumericconverter_test',
      'type': 'executable',
      'dependencies': [
        '../method/method.gyp:engine_lib',
      ],
      'include_dirs': [
        './',
        '<(bridge_dir)',
        '<(engine_dir)/backend',
        '<(engine_dir)/completer',
        '<(engine_dir)/dictionary',
        '<(engine_dir)/editor',
        '<(engine_dir)/entry',
        '<(engine_dir)/keymap',
        '<(engine_dir)/selector',
        '<(engine_dir)/session',
        '<(engine_dir)/skkserv',
        '<(engine_dir)/state',
        '<(engine_dir)/trie',
        '<(engine_dir)/utility',
      ],
      'sources': [
        '<(tests_dir)/SKKNumericConverter_TEST.cpp',
      ],
    },
    
    {
      'target_name': 'skkproxydictionary_test',
      'type': 'executable',
      'dependencies': [
        '../method/method.gyp:engine_lib',
      ],
      'include_dirs': [
        './',
        '<(bridge_dir)',
        '<(engine_dir)/backend',
        '<(engine_dir)/completer',
        '<(engine_dir)/dictionary',
        '<(engine_dir)/editor',
        '<(engine_dir)/entry',
        '<(engine_dir)/keymap',
        '<(engine_dir)/selector',
        '<(engine_dir)/session',
        '<(engine_dir)/skkserv',
        '<(engine_dir)/state',
        '<(engine_dir)/trie',
        '<(engine_dir)/utility',
      ],
      'sources': [
        '<(tests_dir)/SKKProxyDictionary_TEST.cpp',
      ],
    },
    
    {
      'target_name': 'skkromankanaconverter_test',
      'type': 'executable',
      'dependencies': [
        '../method/method.gyp:engine_lib',
      ],
      'include_dirs': [
        './',
        '<(bridge_dir)',
        '<(engine_dir)/backend',
        '<(engine_dir)/completer',
        '<(engine_dir)/dictionary',
        '<(engine_dir)/editor',
        '<(engine_dir)/entry',
        '<(engine_dir)/keymap',
        '<(engine_dir)/selector',
        '<(engine_dir)/session',
        '<(engine_dir)/skkserv',
        '<(engine_dir)/state',
        '<(engine_dir)/trie',
        '<(engine_dir)/utility',
      ],
      'sources': [
        '<(tests_dir)/SKKRomanKanaConverter_TEST.cpp',
      ],
    },
    
    {
      'target_name': 'skkselector_test',
      'type': 'executable',
      'dependencies': [
        '../method/method.gyp:engine_lib',
      ],
      'include_dirs': [
        './',
        '<(bridge_dir)',
        '<(engine_dir)/backend',
        '<(engine_dir)/completer',
        '<(engine_dir)/dictionary',
        '<(engine_dir)/editor',
        '<(engine_dir)/entry',
        '<(engine_dir)/keymap',
        '<(engine_dir)/selector',
        '<(engine_dir)/session',
        '<(engine_dir)/skkserv',
        '<(engine_dir)/state',
        '<(engine_dir)/trie',
        '<(engine_dir)/utility',
      ],
      'sources': [
        '<(tests_dir)/SKKSelector_TEST.cpp',
      ],
    },
    
    {
      'target_name': 'skktrie_test',
      'type': 'executable',
      'dependencies': [
        '../method/method.gyp:engine_lib',
      ],
      'include_dirs': [
        './',
        '<(bridge_dir)',
        '<(engine_dir)/backend',
        '<(engine_dir)/completer',
        '<(engine_dir)/dictionary',
        '<(engine_dir)/editor',
        '<(engine_dir)/entry',
        '<(engine_dir)/keymap',
        '<(engine_dir)/selector',
        '<(engine_dir)/session',
        '<(engine_dir)/skkserv',
        '<(engine_dir)/state',
        '<(engine_dir)/trie',
        '<(engine_dir)/utility',
      ],
      'sources': [
        '<(tests_dir)/SKKTrie_TEST.cpp',
      ],
    },
    
    {
      'target_name': 'skkuserdictionary_test',
      'type': 'executable',
      'dependencies': [
        '../method/method.gyp:engine_lib',
      ],
      'include_dirs': [
        './',
        '<(bridge_dir)',
        '<(engine_dir)/backend',
        '<(engine_dir)/completer',
        '<(engine_dir)/dictionary',
        '<(engine_dir)/editor',
        '<(engine_dir)/entry',
        '<(engine_dir)/keymap',
        '<(engine_dir)/selector',
        '<(engine_dir)/session',
        '<(engine_dir)/skkserv',
        '<(engine_dir)/state',
        '<(engine_dir)/trie',
        '<(engine_dir)/utility',
      ],
      'sources': [
        '<(tests_dir)/SKKUserDictionary_TEST.cpp',
      ],
    },
    
    {
      'target_name': 'skkwindowselector_test',
      'type': 'executable',
      'dependencies': [
        '../method/method.gyp:engine_lib',
      ],
      'include_dirs': [
        './',
        '<(bridge_dir)',
        '<(engine_dir)/backend',
        '<(engine_dir)/completer',
        '<(engine_dir)/dictionary',
        '<(engine_dir)/editor',
        '<(engine_dir)/entry',
        '<(engine_dir)/keymap',
        '<(engine_dir)/selector',
        '<(engine_dir)/session',
        '<(engine_dir)/skkserv',
        '<(engine_dir)/state',
        '<(engine_dir)/trie',
        '<(engine_dir)/utility',
      ],
      'sources': [
        '<(tests_dir)/SKKWindowSelector_TEST.cpp',
      ],
    },
    
    {
      'target_name': 'socketutil_test',
      'type': 'executable',
      'dependencies': [
        '../method/method.gyp:engine_lib',
      ],
      'include_dirs': [
        './',
        '<(bridge_dir)',
        '<(engine_dir)/backend',
        '<(engine_dir)/completer',
        '<(engine_dir)/dictionary',
        '<(engine_dir)/editor',
        '<(engine_dir)/entry',
        '<(engine_dir)/keymap',
        '<(engine_dir)/selector',
        '<(engine_dir)/session',
        '<(engine_dir)/skkserv',
        '<(engine_dir)/state',
        '<(engine_dir)/trie',
        '<(engine_dir)/utility',
      ],
      'sources': [
        '<(tests_dir)/socketutil_TEST.cpp',
      ],
    },
    
    {
      'target_name': 'stringutil_test',
      'type': 'executable',
      'dependencies': [
        '../method/method.gyp:engine_lib',
      ],
      'include_dirs': [
        './',
        '<(bridge_dir)',
        '<(engine_dir)/backend',
        '<(engine_dir)/completer',
        '<(engine_dir)/dictionary',
        '<(engine_dir)/editor',
        '<(engine_dir)/entry',
        '<(engine_dir)/keymap',
        '<(engine_dir)/selector',
        '<(engine_dir)/session',
        '<(engine_dir)/skkserv',
        '<(engine_dir)/state',
        '<(engine_dir)/trie',
        '<(engine_dir)/utility',
      ],
      'sources': [
        '<(tests_dir)/stringutil_TEST.cpp',
      ],
    },
    {
      'target_name': 'utf8util_test',
      'type': 'executable',
      'dependencies': [
        '../method/method.gyp:engine_lib',
      ],
      'include_dirs': [
        './',
        '<(bridge_dir)',
        '<(engine_dir)/backend',
        '<(engine_dir)/completer',
        '<(engine_dir)/dictionary',
        '<(engine_dir)/editor',
        '<(engine_dir)/entry',
        '<(engine_dir)/keymap',
        '<(engine_dir)/selector',
        '<(engine_dir)/session',
        '<(engine_dir)/skkserv',
        '<(engine_dir)/state',
        '<(engine_dir)/trie',
        '<(engine_dir)/utility',
      ],
      'sources': [
        '<(tests_dir)/utf8util_TEST.cpp',
      ],
    },
  ]
}
